hlc_barrel_compact_ACR_556_compatible_weapons = [
    "hlc_rifle_ACR68_SBR_black",
    "hlc_rifle_ACR68_SBR_black_grip",
    "hlc_rifle_ACR68_SBR_black_grip2",
    "hlc_rifle_ACR68_SBR_black_grip3",

    "hlc_rifle_ACR68_SBR_green",
    "hlc_rifle_ACR68_SBR_green_grip",
    "hlc_rifle_ACR68_SBR_green_grip2",
    "hlc_rifle_ACR68_SBR_green_grip3",

    "hlc_rifle_ACR68_SBR_tan",
    "hlc_rifle_ACR68_SBR_tan_grip",
    "hlc_rifle_ACR68_SBR_tan_grip2",
    "hlc_rifle_ACR68_SBR_tan_grip3",

    "hlc_rifle_ACR68_GL_SBR_black",
    "hlc_rifle_ACR68_GL_SBR_green",
    "hlc_rifle_ACR68_GL_SBR_tan",

    "hlc_rifle_ACR_Carb_black",
    "hlc_rifle_ACR_carb_black_grip",
    "hlc_rifle_ACR_carb_black_grip2",
    "hlc_rifle_ACR_carb_black_grip3",
    "hlc_rifle_ACR_Carb_black_x15",
    "hlc_rifle_ACR_carb_black_x15_grip",
    "hlc_rifle_ACR_carb_black_x15_grip2",
    "hlc_rifle_ACR_carb_black_x15_grip3",

    "hlc_rifle_ACR_Carb_green",
    "hlc_rifle_ACR_carb_green_grip",
    "hlc_rifle_ACR_carb_green_grip2",
    "hlc_rifle_ACR_carb_green_grip3",
    "hlc_rifle_ACR_Carb_green_x15",
    "hlc_rifle_ACR_carb_green_x15_grip",
    "hlc_rifle_ACR_carb_green_x15_grip2",
    "hlc_rifle_ACR_carb_green_x15_grip3",

    "hlc_rifle_ACR_Carb_tan",
    "hlc_rifle_ACR_carb_tan_grip",
    "hlc_rifle_ACR_carb_tan_grip2",
    "hlc_rifle_ACR_carb_tan_grip3",
    "hlc_rifle_ACR_Carb_tan_x15",
    "hlc_rifle_ACR_carb_tan_x15_grip",
    "hlc_rifle_ACR_carb_tan_x15_grip2",
    "hlc_rifle_ACR_carb_tan_x15_grip3",

    "hlc_rifle_ACR_GL_Carb_black",
    "hlc_rifle_ACR_GL_Carb_green",
    "hlc_rifle_ACR_GL_Carb_tan",

    "hlc_rifle_ACR68_Carb_black",
    "hlc_rifle_ACR68_carb_black_grip",
    "hlc_rifle_ACR68_carb_black_grip2",
    "hlc_rifle_ACR68_carb_black_grip3",

    "hlc_rifle_ACR68_Carb_green",
    "hlc_rifle_ACR68_carb_green_grip",
    "hlc_rifle_ACR68_carb_green_grip2",
    "hlc_rifle_ACR68_carb_green_grip3",

    "hlc_rifle_ACR68_Carb_tan",
    "hlc_rifle_ACR68_carb_tan_grip",
    "hlc_rifle_ACR68_carb_tan_grip2",
    "hlc_rifle_ACR68_carb_tan_grip3",

    "hlc_rifle_ACR68_GL_Carb_black",
    "hlc_rifle_ACR68_GL_Carb_green",
    "hlc_rifle_ACR68_GL_Carb_tan",

    "hlc_rifle_ACR_MID_black",
    "hlc_rifle_ACR_MID_black_grip",
    "hlc_rifle_ACR_MID_black_grip2",
    "hlc_rifle_ACR_MID_black_grip3",
    "hlc_rifle_ACR_MID_black_x15",
    "hlc_rifle_ACR_MID_black_x15_grip",
    "hlc_rifle_ACR_MID_black_x15_grip2",
    "hlc_rifle_ACR_MID_black_x15_grip3",

    "hlc_rifle_ACR_MID_green",
    "hlc_rifle_ACR_MID_green_grip",
    "hlc_rifle_ACR_MID_green_grip2",
    "hlc_rifle_ACR_MID_green_grip3",
    "hlc_rifle_ACR_MID_green_x15",
    "hlc_rifle_ACR_MID_green_x15_grip",
    "hlc_rifle_ACR_MID_green_x15_grip2",
    "hlc_rifle_ACR_MID_green_x15_grip3",

    "hlc_rifle_ACR_MID_tan",
    "hlc_rifle_ACR_MID_tan_grip",
    "hlc_rifle_ACR_MID_tan_grip2",
    "hlc_rifle_ACR_MID_tan_grip3",
    "hlc_rifle_ACR_MID_tan_x15",
    "hlc_rifle_ACR_MID_tan_x15_grip",
    "hlc_rifle_ACR_MID_tan_x15_grip2",
    "hlc_rifle_ACR_MID_tan_x15_grip3",

    "hlc_rifle_ACR_GL_mid_black",
    "hlc_rifle_ACR_GL_mid_green",
    "hlc_rifle_ACR_GL_mid_tan",

    "hlc_rifle_ACR68_MID_black",
    "hlc_rifle_ACR68_MID_black_grip",
    "hlc_rifle_ACR68_MID_black_grip2",
    "hlc_rifle_ACR68_MID_black_grip3",

    "hlc_rifle_ACR68_MID_green",
    "hlc_rifle_ACR68_MID_green_grip",
    "hlc_rifle_ACR68_MID_green_grip2",
    "hlc_rifle_ACR68_MID_green_grip3",

    "hlc_rifle_ACR68_MID_tan",
    "hlc_rifle_ACR68_MID_tan_grip",
    "hlc_rifle_ACR68_MID_tan_grip2",
    "hlc_rifle_ACR68_MID_tan_grip3",

    "hlc_rifle_ACR68_GL_mid_black",
    "hlc_rifle_ACR68_GL_mid_green",
    "hlc_rifle_ACR68_GL_mid_tan",

    "hlc_rifle_ACR_full_black",
    "hlc_rifle_ACR_Full_black_grip",
    "hlc_rifle_ACR_Full_black_grip2",
    "hlc_rifle_ACR_Full_black_grip3",
    "hlc_rifle_ACR_full_black_x15",
    "hlc_rifle_ACR_Full_black_x15_grip",
    "hlc_rifle_ACR_Full_black_x15_grip2",
    "hlc_rifle_ACR_Full_black_x15_grip3",

    "hlc_rifle_ACR_full_green",
    "hlc_rifle_ACR_Full_green_grip",
    "hlc_rifle_ACR_Full_green_grip2",
    "hlc_rifle_ACR_Full_green_grip3",
    "hlc_rifle_ACR_full_green_x15",
    "hlc_rifle_ACR_Full_green_x15_grip",
    "hlc_rifle_ACR_Full_green_x15_grip2",
    "hlc_rifle_ACR_Full_green_x15_grip3",

    "hlc_rifle_ACR_full_tan",
    "hlc_rifle_ACR_Full_tan_grip",
    "hlc_rifle_ACR_Full_tan_grip2",
    "hlc_rifle_ACR_Full_tan_grip3",
    "hlc_rifle_ACR_full_tan_x15",
    "hlc_rifle_ACR_Full_tan_x15_grip",
    "hlc_rifle_ACR_Full_tan_x15_grip2",
    "hlc_rifle_ACR_Full_tan_x15_grip3",

    "hlc_rifle_ACR68_full_black",
    "hlc_rifle_ACR68_full_black_grip",
    "hlc_rifle_ACR68_full_black_grip2",
    "hlc_rifle_ACR68_full_black_grip3",

    "hlc_rifle_ACR68_full_green",
    "hlc_rifle_ACR68_full_green_grip",
    "hlc_rifle_ACR68_full_green_grip2",
    "hlc_rifle_ACR68_full_green_grip3",

    "hlc_rifle_ACR68_full_tan",
    "hlc_rifle_ACR68_full_tan_grip",
    "hlc_rifle_ACR68_full_tan_grip2",
    "hlc_rifle_ACR68_full_tan_grip3"
];

hlc_barrel_carbine_ACR_556_compatible_weapons = [
    "hlc_rifle_ACR_SBR_black",
    "hlc_rifle_ACR_SBR_black_grip",
    "hlc_rifle_ACR_SBR_black_grip2",
    "hlc_rifle_ACR_SBR_black_grip3",
    "hlc_rifle_ACR_SBR_black_x15",
    "hlc_rifle_ACR_SBR_black_x15_grip",
    "hlc_rifle_ACR_SBR_black_x15_grip2",
    "hlc_rifle_ACR_SBR_black_x15_grip3",

    "hlc_rifle_ACR_SBR_green",
    "hlc_rifle_ACR_SBR_green_grip",
    "hlc_rifle_ACR_SBR_green_grip2",
    "hlc_rifle_ACR_SBR_green_grip3",
    "hlc_rifle_ACR_SBR_green_x15",
    "hlc_rifle_ACR_SBR_green_x15_grip",
    "hlc_rifle_ACR_SBR_green_x15_grip2",
    "hlc_rifle_ACR_SBR_green_x15_grip3",

    "hlc_rifle_ACR_SBR_tan",
    "hlc_rifle_ACR_SBR_tan_grip",
    "hlc_rifle_ACR_SBR_tan_grip2",
    "hlc_rifle_ACR_SBR_tan_grip3",
    "hlc_rifle_ACR_SBR_tan_x15",
    "hlc_rifle_ACR_SBR_tan_x15_grip",
    "hlc_rifle_ACR_SBR_tan_x15_grip2",
    "hlc_rifle_ACR_SBR_tan_x15_grip3",

    "hlc_rifle_ACR_GL_SBR_black",
    "hlc_rifle_ACR_GL_SBR_green",
    "hlc_rifle_ACR_GL_SBR_tan",

    "hlc_rifle_ACR68_SBR_black",
    "hlc_rifle_ACR68_SBR_black_grip",
    "hlc_rifle_ACR68_SBR_black_grip2",
    "hlc_rifle_ACR68_SBR_black_grip3",

    "hlc_rifle_ACR68_SBR_green",
    "hlc_rifle_ACR68_SBR_green_grip",
    "hlc_rifle_ACR68_SBR_green_grip2",
    "hlc_rifle_ACR68_SBR_green_grip3",

    "hlc_rifle_ACR68_SBR_tan",
    "hlc_rifle_ACR68_SBR_tan_grip",
    "hlc_rifle_ACR68_SBR_tan_grip2",
    "hlc_rifle_ACR68_SBR_tan_grip3",

    "hlc_rifle_ACR68_GL_SBR_black",
    "hlc_rifle_ACR68_GL_SBR_green",
    "hlc_rifle_ACR68_GL_SBR_tan",

    "hlc_rifle_ACR68_Carb_black",
    "hlc_rifle_ACR68_carb_black_grip",
    "hlc_rifle_ACR68_carb_black_grip2",
    "hlc_rifle_ACR68_carb_black_grip3",

    "hlc_rifle_ACR68_Carb_green",
    "hlc_rifle_ACR68_carb_green_grip",
    "hlc_rifle_ACR68_carb_green_grip2",
    "hlc_rifle_ACR68_carb_green_grip3",

    "hlc_rifle_ACR68_Carb_tan",
    "hlc_rifle_ACR68_carb_tan_grip",
    "hlc_rifle_ACR68_carb_tan_grip2",
    "hlc_rifle_ACR68_carb_tan_grip3",

    "hlc_rifle_ACR68_GL_Carb_black",
    "hlc_rifle_ACR68_GL_Carb_green",
    "hlc_rifle_ACR68_GL_Carb_tan",

    "hlc_rifle_ACR_MID_black",
    "hlc_rifle_ACR_MID_black_grip",
    "hlc_rifle_ACR_MID_black_grip2",
    "hlc_rifle_ACR_MID_black_grip3",
    "hlc_rifle_ACR_MID_black_x15",
    "hlc_rifle_ACR_MID_black_x15_grip",
    "hlc_rifle_ACR_MID_black_x15_grip2",
    "hlc_rifle_ACR_MID_black_x15_grip3",

    "hlc_rifle_ACR_MID_green",
    "hlc_rifle_ACR_MID_green_grip",
    "hlc_rifle_ACR_MID_green_grip2",
    "hlc_rifle_ACR_MID_green_grip3",
    "hlc_rifle_ACR_MID_green_x15",
    "hlc_rifle_ACR_MID_green_x15_grip",
    "hlc_rifle_ACR_MID_green_x15_grip2",
    "hlc_rifle_ACR_MID_green_x15_grip3",

    "hlc_rifle_ACR_MID_tan",
    "hlc_rifle_ACR_MID_tan_grip",
    "hlc_rifle_ACR_MID_tan_grip2",
    "hlc_rifle_ACR_MID_tan_grip3",
    "hlc_rifle_ACR_MID_tan_x15",
    "hlc_rifle_ACR_MID_tan_x15_grip",
    "hlc_rifle_ACR_MID_tan_x15_grip2",
    "hlc_rifle_ACR_MID_tan_x15_grip3",

    "hlc_rifle_ACR_GL_mid_black",
    "hlc_rifle_ACR_GL_mid_green",
    "hlc_rifle_ACR_GL_mid_tan",

    "hlc_rifle_ACR68_MID_black",
    "hlc_rifle_ACR68_MID_black_grip",
    "hlc_rifle_ACR68_MID_black_grip2",
    "hlc_rifle_ACR68_MID_black_grip3",

    "hlc_rifle_ACR68_MID_green",
    "hlc_rifle_ACR68_MID_green_grip",
    "hlc_rifle_ACR68_MID_green_grip2",
    "hlc_rifle_ACR68_MID_green_grip3",

    "hlc_rifle_ACR68_MID_tan",
    "hlc_rifle_ACR68_MID_tan_grip",
    "hlc_rifle_ACR68_MID_tan_grip2",
    "hlc_rifle_ACR68_MID_tan_grip3",

    "hlc_rifle_ACR68_GL_mid_black",
    "hlc_rifle_ACR68_GL_mid_green",
    "hlc_rifle_ACR68_GL_mid_tan",

    "hlc_rifle_ACR_full_black",
    "hlc_rifle_ACR_Full_black_grip",
    "hlc_rifle_ACR_Full_black_grip2",
    "hlc_rifle_ACR_Full_black_grip3",
    "hlc_rifle_ACR_full_black_x15",
    "hlc_rifle_ACR_Full_black_x15_grip",
    "hlc_rifle_ACR_Full_black_x15_grip2",
    "hlc_rifle_ACR_Full_black_x15_grip3",

    "hlc_rifle_ACR_full_green",
    "hlc_rifle_ACR_Full_green_grip",
    "hlc_rifle_ACR_Full_green_grip2",
    "hlc_rifle_ACR_Full_green_grip3",
    "hlc_rifle_ACR_full_green_x15",
    "hlc_rifle_ACR_Full_green_x15_grip",
    "hlc_rifle_ACR_Full_green_x15_grip2",
    "hlc_rifle_ACR_Full_green_x15_grip3",

    "hlc_rifle_ACR_full_tan",
    "hlc_rifle_ACR_Full_tan_grip",
    "hlc_rifle_ACR_Full_tan_grip2",
    "hlc_rifle_ACR_Full_tan_grip3",
    "hlc_rifle_ACR_full_tan_x15",
    "hlc_rifle_ACR_Full_tan_x15_grip",
    "hlc_rifle_ACR_Full_tan_x15_grip2",
    "hlc_rifle_ACR_Full_tan_x15_grip3",

    "hlc_rifle_ACR68_full_black",
    "hlc_rifle_ACR68_full_black_grip",
    "hlc_rifle_ACR68_full_black_grip2",
    "hlc_rifle_ACR68_full_black_grip3",

    "hlc_rifle_ACR68_full_green",
    "hlc_rifle_ACR68_full_green_grip",
    "hlc_rifle_ACR68_full_green_grip2",
    "hlc_rifle_ACR68_full_green_grip3",

    "hlc_rifle_ACR68_full_tan",
    "hlc_rifle_ACR68_full_tan_grip",
    "hlc_rifle_ACR68_full_tan_grip2",
    "hlc_rifle_ACR68_full_tan_grip3"
];

hlc_barrel_mid_ACR_556_compatible_weapons = [
    "hlc_rifle_ACR_SBR_black",
    "hlc_rifle_ACR_SBR_black_grip",
    "hlc_rifle_ACR_SBR_black_grip2",
    "hlc_rifle_ACR_SBR_black_grip3",
    "hlc_rifle_ACR_SBR_black_x15",
    "hlc_rifle_ACR_SBR_black_x15_grip",
    "hlc_rifle_ACR_SBR_black_x15_grip2",
    "hlc_rifle_ACR_SBR_black_x15_grip3",

    "hlc_rifle_ACR_SBR_green",
    "hlc_rifle_ACR_SBR_green_grip",
    "hlc_rifle_ACR_SBR_green_grip2",
    "hlc_rifle_ACR_SBR_green_grip3",
    "hlc_rifle_ACR_SBR_green_x15",
    "hlc_rifle_ACR_SBR_green_x15_grip",
    "hlc_rifle_ACR_SBR_green_x15_grip2",
    "hlc_rifle_ACR_SBR_green_x15_grip3",

    "hlc_rifle_ACR_SBR_tan",
    "hlc_rifle_ACR_SBR_tan_grip",
    "hlc_rifle_ACR_SBR_tan_grip2",
    "hlc_rifle_ACR_SBR_tan_grip3",
    "hlc_rifle_ACR_SBR_tan_x15",
    "hlc_rifle_ACR_SBR_tan_x15_grip",
    "hlc_rifle_ACR_SBR_tan_x15_grip2",
    "hlc_rifle_ACR_SBR_tan_x15_grip3",

    "hlc_rifle_ACR_GL_SBR_black",
    "hlc_rifle_ACR_GL_SBR_green",
    "hlc_rifle_ACR_GL_SBR_tan",

    "hlc_rifle_ACR68_SBR_black",
    "hlc_rifle_ACR68_SBR_black_grip",
    "hlc_rifle_ACR68_SBR_black_grip2",
    "hlc_rifle_ACR68_SBR_black_grip3",

    "hlc_rifle_ACR68_SBR_green",
    "hlc_rifle_ACR68_SBR_green_grip",
    "hlc_rifle_ACR68_SBR_green_grip2",
    "hlc_rifle_ACR68_SBR_green_grip3",

    "hlc_rifle_ACR68_SBR_tan",
    "hlc_rifle_ACR68_SBR_tan_grip",
    "hlc_rifle_ACR68_SBR_tan_grip2",
    "hlc_rifle_ACR68_SBR_tan_grip3",

    "hlc_rifle_ACR68_GL_SBR_black",
    "hlc_rifle_ACR68_GL_SBR_green",
    "hlc_rifle_ACR68_GL_SBR_tan",

    "hlc_rifle_ACR_Carb_black",
    "hlc_rifle_ACR_carb_black_grip",
    "hlc_rifle_ACR_carb_black_grip2",
    "hlc_rifle_ACR_carb_black_grip3",
    "hlc_rifle_ACR_Carb_black_x15",
    "hlc_rifle_ACR_carb_black_x15_grip",
    "hlc_rifle_ACR_carb_black_x15_grip2",
    "hlc_rifle_ACR_carb_black_x15_grip3",

    "hlc_rifle_ACR_Carb_green",
    "hlc_rifle_ACR_carb_green_grip",
    "hlc_rifle_ACR_carb_green_grip2",
    "hlc_rifle_ACR_carb_green_grip3",
    "hlc_rifle_ACR_Carb_green_x15",
    "hlc_rifle_ACR_carb_green_x15_grip",
    "hlc_rifle_ACR_carb_green_x15_grip2",
    "hlc_rifle_ACR_carb_green_x15_grip3",

    "hlc_rifle_ACR_Carb_tan",
    "hlc_rifle_ACR_carb_tan_grip",
    "hlc_rifle_ACR_carb_tan_grip2",
    "hlc_rifle_ACR_carb_tan_grip3",
    "hlc_rifle_ACR_Carb_tan_x15",
    "hlc_rifle_ACR_carb_tan_x15_grip",
    "hlc_rifle_ACR_carb_tan_x15_grip2",
    "hlc_rifle_ACR_carb_tan_x15_grip3",

    "hlc_rifle_ACR_GL_Carb_black",
    "hlc_rifle_ACR_GL_Carb_green",
    "hlc_rifle_ACR_GL_Carb_tan",

    "hlc_rifle_ACR68_Carb_black",
    "hlc_rifle_ACR68_carb_black_grip",
    "hlc_rifle_ACR68_carb_black_grip2",
    "hlc_rifle_ACR68_carb_black_grip3",

    "hlc_rifle_ACR68_Carb_green",
    "hlc_rifle_ACR68_carb_green_grip",
    "hlc_rifle_ACR68_carb_green_grip2",
    "hlc_rifle_ACR68_carb_green_grip3",

    "hlc_rifle_ACR68_Carb_tan",
    "hlc_rifle_ACR68_carb_tan_grip",
    "hlc_rifle_ACR68_carb_tan_grip2",
    "hlc_rifle_ACR68_carb_tan_grip3",

    "hlc_rifle_ACR68_GL_Carb_black",
    "hlc_rifle_ACR68_GL_Carb_green",
    "hlc_rifle_ACR68_GL_Carb_tan",

    "hlc_rifle_ACR68_MID_black",
    "hlc_rifle_ACR68_MID_black_grip",
    "hlc_rifle_ACR68_MID_black_grip2",
    "hlc_rifle_ACR68_MID_black_grip3",

    "hlc_rifle_ACR68_MID_green",
    "hlc_rifle_ACR68_MID_green_grip",
    "hlc_rifle_ACR68_MID_green_grip2",
    "hlc_rifle_ACR68_MID_green_grip3",

    "hlc_rifle_ACR68_MID_tan",
    "hlc_rifle_ACR68_MID_tan_grip",
    "hlc_rifle_ACR68_MID_tan_grip2",
    "hlc_rifle_ACR68_MID_tan_grip3",

    "hlc_rifle_ACR68_GL_mid_black",
    "hlc_rifle_ACR68_GL_mid_green",
    "hlc_rifle_ACR68_GL_mid_tan",

    "hlc_rifle_ACR_full_black",
    "hlc_rifle_ACR_Full_black_grip",
    "hlc_rifle_ACR_Full_black_grip2",
    "hlc_rifle_ACR_Full_black_grip3",
    "hlc_rifle_ACR_full_black_x15",
    "hlc_rifle_ACR_Full_black_x15_grip",
    "hlc_rifle_ACR_Full_black_x15_grip2",
    "hlc_rifle_ACR_Full_black_x15_grip3",

    "hlc_rifle_ACR_full_green",
    "hlc_rifle_ACR_Full_green_grip",
    "hlc_rifle_ACR_Full_green_grip2",
    "hlc_rifle_ACR_Full_green_grip3",
    "hlc_rifle_ACR_full_green_x15",
    "hlc_rifle_ACR_Full_green_x15_grip",
    "hlc_rifle_ACR_Full_green_x15_grip2",
    "hlc_rifle_ACR_Full_green_x15_grip3",

    "hlc_rifle_ACR_full_tan",
    "hlc_rifle_ACR_Full_tan_grip",
    "hlc_rifle_ACR_Full_tan_grip2",
    "hlc_rifle_ACR_Full_tan_grip3",
    "hlc_rifle_ACR_full_tan_x15",
    "hlc_rifle_ACR_Full_tan_x15_grip",
    "hlc_rifle_ACR_Full_tan_x15_grip2",
    "hlc_rifle_ACR_Full_tan_x15_grip3",

    "hlc_rifle_ACR68_full_black",
    "hlc_rifle_ACR68_full_black_grip",
    "hlc_rifle_ACR68_full_black_grip2",
    "hlc_rifle_ACR68_full_black_grip3",

    "hlc_rifle_ACR68_full_green",
    "hlc_rifle_ACR68_full_green_grip",
    "hlc_rifle_ACR68_full_green_grip2",
    "hlc_rifle_ACR68_full_green_grip3",

    "hlc_rifle_ACR68_full_tan",
    "hlc_rifle_ACR68_full_tan_grip",
    "hlc_rifle_ACR68_full_tan_grip2",
    "hlc_rifle_ACR68_full_tan_grip3"
];

hlc_barrel_full_ACR_556_compatible_weapons = [
    "hlc_rifle_ACR_SBR_black",
    "hlc_rifle_ACR_SBR_black_grip",
    "hlc_rifle_ACR_SBR_black_grip2",
    "hlc_rifle_ACR_SBR_black_grip3",
    "hlc_rifle_ACR_SBR_black_x15",
    "hlc_rifle_ACR_SBR_black_x15_grip",
    "hlc_rifle_ACR_SBR_black_x15_grip2",
    "hlc_rifle_ACR_SBR_black_x15_grip3",

    "hlc_rifle_ACR_SBR_green",
    "hlc_rifle_ACR_SBR_green_grip",
    "hlc_rifle_ACR_SBR_green_grip2",
    "hlc_rifle_ACR_SBR_green_grip3",
    "hlc_rifle_ACR_SBR_green_x15",
    "hlc_rifle_ACR_SBR_green_x15_grip",
    "hlc_rifle_ACR_SBR_green_x15_grip2",
    "hlc_rifle_ACR_SBR_green_x15_grip3",

    "hlc_rifle_ACR_SBR_tan",
    "hlc_rifle_ACR_SBR_tan_grip",
    "hlc_rifle_ACR_SBR_tan_grip2",
    "hlc_rifle_ACR_SBR_tan_grip3",
    "hlc_rifle_ACR_SBR_tan_x15",
    "hlc_rifle_ACR_SBR_tan_x15_grip",
    "hlc_rifle_ACR_SBR_tan_x15_grip2",
    "hlc_rifle_ACR_SBR_tan_x15_grip3",

    "hlc_rifle_ACR_GL_SBR_black",
    "hlc_rifle_ACR_GL_SBR_green",
    "hlc_rifle_ACR_GL_SBR_tan",

    "hlc_rifle_ACR68_SBR_black",
    "hlc_rifle_ACR68_SBR_black_grip",
    "hlc_rifle_ACR68_SBR_black_grip2",
    "hlc_rifle_ACR68_SBR_black_grip3",

    "hlc_rifle_ACR68_SBR_green",
    "hlc_rifle_ACR68_SBR_green_grip",
    "hlc_rifle_ACR68_SBR_green_grip2",
    "hlc_rifle_ACR68_SBR_green_grip3",

    "hlc_rifle_ACR68_SBR_tan",
    "hlc_rifle_ACR68_SBR_tan_grip",
    "hlc_rifle_ACR68_SBR_tan_grip2",
    "hlc_rifle_ACR68_SBR_tan_grip3",

    "hlc_rifle_ACR68_GL_SBR_black",
    "hlc_rifle_ACR68_GL_SBR_green",
    "hlc_rifle_ACR68_GL_SBR_tan",

    "hlc_rifle_ACR_Carb_black",
    "hlc_rifle_ACR_carb_black_grip",
    "hlc_rifle_ACR_carb_black_grip2",
    "hlc_rifle_ACR_carb_black_grip3",
    "hlc_rifle_ACR_Carb_black_x15",
    "hlc_rifle_ACR_carb_black_x15_grip",
    "hlc_rifle_ACR_carb_black_x15_grip2",
    "hlc_rifle_ACR_carb_black_x15_grip3",

    "hlc_rifle_ACR_Carb_green",
    "hlc_rifle_ACR_carb_green_grip",
    "hlc_rifle_ACR_carb_green_grip2",
    "hlc_rifle_ACR_carb_green_grip3",
    "hlc_rifle_ACR_Carb_green_x15",
    "hlc_rifle_ACR_carb_green_x15_grip",
    "hlc_rifle_ACR_carb_green_x15_grip2",
    "hlc_rifle_ACR_carb_green_x15_grip3",

    "hlc_rifle_ACR_Carb_tan",
    "hlc_rifle_ACR_carb_tan_grip",
    "hlc_rifle_ACR_carb_tan_grip2",
    "hlc_rifle_ACR_carb_tan_grip3",
    "hlc_rifle_ACR_Carb_tan_x15",
    "hlc_rifle_ACR_carb_tan_x15_grip",
    "hlc_rifle_ACR_carb_tan_x15_grip2",
    "hlc_rifle_ACR_carb_tan_x15_grip3",

    "hlc_rifle_ACR_GL_Carb_black",
    "hlc_rifle_ACR_GL_Carb_green",
    "hlc_rifle_ACR_GL_Carb_tan",

    "hlc_rifle_ACR68_Carb_black",
    "hlc_rifle_ACR68_carb_black_grip",
    "hlc_rifle_ACR68_carb_black_grip2",
    "hlc_rifle_ACR68_carb_black_grip3",

    "hlc_rifle_ACR68_Carb_green",
    "hlc_rifle_ACR68_carb_green_grip",
    "hlc_rifle_ACR68_carb_green_grip2",
    "hlc_rifle_ACR68_carb_green_grip3",

    "hlc_rifle_ACR68_Carb_tan",
    "hlc_rifle_ACR68_carb_tan_grip",
    "hlc_rifle_ACR68_carb_tan_grip2",
    "hlc_rifle_ACR68_carb_tan_grip3",

    "hlc_rifle_ACR68_GL_Carb_black",
    "hlc_rifle_ACR68_GL_Carb_green",
    "hlc_rifle_ACR68_GL_Carb_tan",

    "hlc_rifle_ACR_MID_black",
    "hlc_rifle_ACR_MID_black_grip",
    "hlc_rifle_ACR_MID_black_grip2",
    "hlc_rifle_ACR_MID_black_grip3",
    "hlc_rifle_ACR_MID_black_x15",
    "hlc_rifle_ACR_MID_black_x15_grip",
    "hlc_rifle_ACR_MID_black_x15_grip2",
    "hlc_rifle_ACR_MID_black_x15_grip3",

    "hlc_rifle_ACR_MID_green",
    "hlc_rifle_ACR_MID_green_grip",
    "hlc_rifle_ACR_MID_green_grip2",
    "hlc_rifle_ACR_MID_green_grip3",
    "hlc_rifle_ACR_MID_green_x15",
    "hlc_rifle_ACR_MID_green_x15_grip",
    "hlc_rifle_ACR_MID_green_x15_grip2",
    "hlc_rifle_ACR_MID_green_x15_grip3",

    "hlc_rifle_ACR_MID_tan",
    "hlc_rifle_ACR_MID_tan_grip",
    "hlc_rifle_ACR_MID_tan_grip2",
    "hlc_rifle_ACR_MID_tan_grip3",
    "hlc_rifle_ACR_MID_tan_x15",
    "hlc_rifle_ACR_MID_tan_x15_grip",
    "hlc_rifle_ACR_MID_tan_x15_grip2",
    "hlc_rifle_ACR_MID_tan_x15_grip3",

    "hlc_rifle_ACR_GL_mid_black",
    "hlc_rifle_ACR_GL_mid_green",
    "hlc_rifle_ACR_GL_mid_tan",

    "hlc_rifle_ACR68_MID_black",
    "hlc_rifle_ACR68_MID_black_grip",
    "hlc_rifle_ACR68_MID_black_grip2",
    "hlc_rifle_ACR68_MID_black_grip3",

    "hlc_rifle_ACR68_MID_green",
    "hlc_rifle_ACR68_MID_green_grip",
    "hlc_rifle_ACR68_MID_green_grip2",
    "hlc_rifle_ACR68_MID_green_grip3",

    "hlc_rifle_ACR68_MID_tan",
    "hlc_rifle_ACR68_MID_tan_grip",
    "hlc_rifle_ACR68_MID_tan_grip2",
    "hlc_rifle_ACR68_MID_tan_grip3",

    "hlc_rifle_ACR68_GL_mid_black",
    "hlc_rifle_ACR68_GL_mid_green",
    "hlc_rifle_ACR68_GL_mid_tan",

    "hlc_rifle_ACR68_full_black",
    "hlc_rifle_ACR68_full_black_grip",
    "hlc_rifle_ACR68_full_black_grip2",
    "hlc_rifle_ACR68_full_black_grip3",

    "hlc_rifle_ACR68_full_green",
    "hlc_rifle_ACR68_full_green_grip",
    "hlc_rifle_ACR68_full_green_grip2",
    "hlc_rifle_ACR68_full_green_grip3",

    "hlc_rifle_ACR68_full_tan",
    "hlc_rifle_ACR68_full_tan_grip",
    "hlc_rifle_ACR68_full_tan_grip2",
    "hlc_rifle_ACR68_full_tan_grip3"
];

hlc_barrel_compact_ACR_68_compatible_weapons = [
    "hlc_rifle_ACR_SBR_black",
    "hlc_rifle_ACR_SBR_black_grip",
    "hlc_rifle_ACR_SBR_black_grip2",
    "hlc_rifle_ACR_SBR_black_grip3",
    "hlc_rifle_ACR_SBR_black_x15",
    "hlc_rifle_ACR_SBR_black_x15_grip",
    "hlc_rifle_ACR_SBR_black_x15_grip2",
    "hlc_rifle_ACR_SBR_black_x15_grip3",

    "hlc_rifle_ACR_SBR_green",
    "hlc_rifle_ACR_SBR_green_grip",
    "hlc_rifle_ACR_SBR_green_grip2",
    "hlc_rifle_ACR_SBR_green_grip3",
    "hlc_rifle_ACR_SBR_green_x15",
    "hlc_rifle_ACR_SBR_green_x15_grip",
    "hlc_rifle_ACR_SBR_green_x15_grip2",
    "hlc_rifle_ACR_SBR_green_x15_grip3",

    "hlc_rifle_ACR_SBR_tan",
    "hlc_rifle_ACR_SBR_tan_grip",
    "hlc_rifle_ACR_SBR_tan_grip2",
    "hlc_rifle_ACR_SBR_tan_grip3",
    "hlc_rifle_ACR_SBR_tan_x15",
    "hlc_rifle_ACR_SBR_tan_x15_grip",
    "hlc_rifle_ACR_SBR_tan_x15_grip2",
    "hlc_rifle_ACR_SBR_tan_x15_grip3",

    "hlc_rifle_ACR_GL_SBR_black",
    "hlc_rifle_ACR_GL_SBR_green",
    "hlc_rifle_ACR_GL_SBR_tan",

    "hlc_rifle_ACR_Carb_black",
    "hlc_rifle_ACR_carb_black_grip",
    "hlc_rifle_ACR_carb_black_grip2",
    "hlc_rifle_ACR_carb_black_grip3",
    "hlc_rifle_ACR_Carb_black_x15",
    "hlc_rifle_ACR_carb_black_x15_grip",
    "hlc_rifle_ACR_carb_black_x15_grip2",
    "hlc_rifle_ACR_carb_black_x15_grip3",

    "hlc_rifle_ACR_Carb_green",
    "hlc_rifle_ACR_carb_green_grip",
    "hlc_rifle_ACR_carb_green_grip2",
    "hlc_rifle_ACR_carb_green_grip3",
    "hlc_rifle_ACR_Carb_green_x15",
    "hlc_rifle_ACR_carb_green_x15_grip",
    "hlc_rifle_ACR_carb_green_x15_grip2",
    "hlc_rifle_ACR_carb_green_x15_grip3",

    "hlc_rifle_ACR_Carb_tan",
    "hlc_rifle_ACR_carb_tan_grip",
    "hlc_rifle_ACR_carb_tan_grip2",
    "hlc_rifle_ACR_carb_tan_grip3",
    "hlc_rifle_ACR_Carb_tan_x15",
    "hlc_rifle_ACR_carb_tan_x15_grip",
    "hlc_rifle_ACR_carb_tan_x15_grip2",
    "hlc_rifle_ACR_carb_tan_x15_grip3",

    "hlc_rifle_ACR_GL_Carb_black",
    "hlc_rifle_ACR_GL_Carb_green",
    "hlc_rifle_ACR_GL_Carb_tan",

    "hlc_rifle_ACR68_Carb_black",
    "hlc_rifle_ACR68_carb_black_grip",
    "hlc_rifle_ACR68_carb_black_grip2",
    "hlc_rifle_ACR68_carb_black_grip3",

    "hlc_rifle_ACR68_Carb_green",
    "hlc_rifle_ACR68_carb_green_grip",
    "hlc_rifle_ACR68_carb_green_grip2",
    "hlc_rifle_ACR68_carb_green_grip3",

    "hlc_rifle_ACR68_Carb_tan",
    "hlc_rifle_ACR68_carb_tan_grip",
    "hlc_rifle_ACR68_carb_tan_grip2",
    "hlc_rifle_ACR68_carb_tan_grip3",

    "hlc_rifle_ACR68_GL_Carb_black",
    "hlc_rifle_ACR68_GL_Carb_green",
    "hlc_rifle_ACR68_GL_Carb_tan",

    "hlc_rifle_ACR_MID_black",
    "hlc_rifle_ACR_MID_black_grip",
    "hlc_rifle_ACR_MID_black_grip2",
    "hlc_rifle_ACR_MID_black_grip3",
    "hlc_rifle_ACR_MID_black_x15",
    "hlc_rifle_ACR_MID_black_x15_grip",
    "hlc_rifle_ACR_MID_black_x15_grip2",
    "hlc_rifle_ACR_MID_black_x15_grip3",

    "hlc_rifle_ACR_MID_green",
    "hlc_rifle_ACR_MID_green_grip",
    "hlc_rifle_ACR_MID_green_grip2",
    "hlc_rifle_ACR_MID_green_grip3",
    "hlc_rifle_ACR_MID_green_x15",
    "hlc_rifle_ACR_MID_green_x15_grip",
    "hlc_rifle_ACR_MID_green_x15_grip2",
    "hlc_rifle_ACR_MID_green_x15_grip3",

    "hlc_rifle_ACR_MID_tan",
    "hlc_rifle_ACR_MID_tan_grip",
    "hlc_rifle_ACR_MID_tan_grip2",
    "hlc_rifle_ACR_MID_tan_grip3",
    "hlc_rifle_ACR_MID_tan_x15",
    "hlc_rifle_ACR_MID_tan_x15_grip",
    "hlc_rifle_ACR_MID_tan_x15_grip2",
    "hlc_rifle_ACR_MID_tan_x15_grip3",

    "hlc_rifle_ACR_GL_mid_black",
    "hlc_rifle_ACR_GL_mid_green",
    "hlc_rifle_ACR_GL_mid_tan",

    "hlc_rifle_ACR68_MID_black",
    "hlc_rifle_ACR68_MID_black_grip",
    "hlc_rifle_ACR68_MID_black_grip2",
    "hlc_rifle_ACR68_MID_black_grip3",

    "hlc_rifle_ACR68_MID_green",
    "hlc_rifle_ACR68_MID_green_grip",
    "hlc_rifle_ACR68_MID_green_grip2",
    "hlc_rifle_ACR68_MID_green_grip3",

    "hlc_rifle_ACR68_MID_tan",
    "hlc_rifle_ACR68_MID_tan_grip",
    "hlc_rifle_ACR68_MID_tan_grip2",
    "hlc_rifle_ACR68_MID_tan_grip3",

    "hlc_rifle_ACR68_GL_mid_black",
    "hlc_rifle_ACR68_GL_mid_green",
    "hlc_rifle_ACR68_GL_mid_tan",

    "hlc_rifle_ACR_full_black",
    "hlc_rifle_ACR_Full_black_grip",
    "hlc_rifle_ACR_Full_black_grip2",
    "hlc_rifle_ACR_Full_black_grip3",
    "hlc_rifle_ACR_full_black_x15",
    "hlc_rifle_ACR_Full_black_x15_grip",
    "hlc_rifle_ACR_Full_black_x15_grip2",
    "hlc_rifle_ACR_Full_black_x15_grip3",

    "hlc_rifle_ACR_full_green",
    "hlc_rifle_ACR_Full_green_grip",
    "hlc_rifle_ACR_Full_green_grip2",
    "hlc_rifle_ACR_Full_green_grip3",
    "hlc_rifle_ACR_full_green_x15",
    "hlc_rifle_ACR_Full_green_x15_grip",
    "hlc_rifle_ACR_Full_green_x15_grip2",
    "hlc_rifle_ACR_Full_green_x15_grip3",

    "hlc_rifle_ACR_full_tan",
    "hlc_rifle_ACR_Full_tan_grip",
    "hlc_rifle_ACR_Full_tan_grip2",
    "hlc_rifle_ACR_Full_tan_grip3",
    "hlc_rifle_ACR_full_tan_x15",
    "hlc_rifle_ACR_Full_tan_x15_grip",
    "hlc_rifle_ACR_Full_tan_x15_grip2",
    "hlc_rifle_ACR_Full_tan_x15_grip3",

    "hlc_rifle_ACR68_full_black",
    "hlc_rifle_ACR68_full_black_grip",
    "hlc_rifle_ACR68_full_black_grip2",
    "hlc_rifle_ACR68_full_black_grip3",

    "hlc_rifle_ACR68_full_green",
    "hlc_rifle_ACR68_full_green_grip",
    "hlc_rifle_ACR68_full_green_grip2",
    "hlc_rifle_ACR68_full_green_grip3",

    "hlc_rifle_ACR68_full_tan",
    "hlc_rifle_ACR68_full_tan_grip",
    "hlc_rifle_ACR68_full_tan_grip2",
    "hlc_rifle_ACR68_full_tan_grip3"
];

hlc_barrel_carbine_ACR_68_compatible_weapons = [
    "hlc_rifle_ACR_SBR_black",
    "hlc_rifle_ACR_SBR_black_grip",
    "hlc_rifle_ACR_SBR_black_grip2",
    "hlc_rifle_ACR_SBR_black_grip3",
    "hlc_rifle_ACR_SBR_black_x15",
    "hlc_rifle_ACR_SBR_black_x15_grip",
    "hlc_rifle_ACR_SBR_black_x15_grip2",
    "hlc_rifle_ACR_SBR_black_x15_grip3",

    "hlc_rifle_ACR_SBR_green",
    "hlc_rifle_ACR_SBR_green_grip",
    "hlc_rifle_ACR_SBR_green_grip2",
    "hlc_rifle_ACR_SBR_green_grip3",
    "hlc_rifle_ACR_SBR_green_x15",
    "hlc_rifle_ACR_SBR_green_x15_grip",
    "hlc_rifle_ACR_SBR_green_x15_grip2",
    "hlc_rifle_ACR_SBR_green_x15_grip3",

    "hlc_rifle_ACR_SBR_tan",
    "hlc_rifle_ACR_SBR_tan_grip",
    "hlc_rifle_ACR_SBR_tan_grip2",
    "hlc_rifle_ACR_SBR_tan_grip3",
    "hlc_rifle_ACR_SBR_tan_x15",
    "hlc_rifle_ACR_SBR_tan_x15_grip",
    "hlc_rifle_ACR_SBR_tan_x15_grip2",
    "hlc_rifle_ACR_SBR_tan_x15_grip3",

    "hlc_rifle_ACR_GL_SBR_black",
    "hlc_rifle_ACR_GL_SBR_green",
    "hlc_rifle_ACR_GL_SBR_tan",

    "hlc_rifle_ACR68_SBR_black",
    "hlc_rifle_ACR68_SBR_black_grip",
    "hlc_rifle_ACR68_SBR_black_grip2",
    "hlc_rifle_ACR68_SBR_black_grip3",

    "hlc_rifle_ACR68_SBR_green",
    "hlc_rifle_ACR68_SBR_green_grip",
    "hlc_rifle_ACR68_SBR_green_grip2",
    "hlc_rifle_ACR68_SBR_green_grip3",

    "hlc_rifle_ACR68_SBR_tan",
    "hlc_rifle_ACR68_SBR_tan_grip",
    "hlc_rifle_ACR68_SBR_tan_grip2",
    "hlc_rifle_ACR68_SBR_tan_grip3",

    "hlc_rifle_ACR68_GL_SBR_black",
    "hlc_rifle_ACR68_GL_SBR_green",
    "hlc_rifle_ACR68_GL_SBR_tan",

    "hlc_rifle_ACR_Carb_black",
    "hlc_rifle_ACR_carb_black_grip",
    "hlc_rifle_ACR_carb_black_grip2",
    "hlc_rifle_ACR_carb_black_grip3",
    "hlc_rifle_ACR_Carb_black_x15",
    "hlc_rifle_ACR_carb_black_x15_grip",
    "hlc_rifle_ACR_carb_black_x15_grip2",
    "hlc_rifle_ACR_carb_black_x15_grip3",

    "hlc_rifle_ACR_Carb_green",
    "hlc_rifle_ACR_carb_green_grip",
    "hlc_rifle_ACR_carb_green_grip2",
    "hlc_rifle_ACR_carb_green_grip3",
    "hlc_rifle_ACR_Carb_green_x15",
    "hlc_rifle_ACR_carb_green_x15_grip",
    "hlc_rifle_ACR_carb_green_x15_grip2",
    "hlc_rifle_ACR_carb_green_x15_grip3",

    "hlc_rifle_ACR_Carb_tan",
    "hlc_rifle_ACR_carb_tan_grip",
    "hlc_rifle_ACR_carb_tan_grip2",
    "hlc_rifle_ACR_carb_tan_grip3",
    "hlc_rifle_ACR_Carb_tan_x15",
    "hlc_rifle_ACR_carb_tan_x15_grip",
    "hlc_rifle_ACR_carb_tan_x15_grip2",
    "hlc_rifle_ACR_carb_tan_x15_grip3",

    "hlc_rifle_ACR_GL_Carb_black",
    "hlc_rifle_ACR_GL_Carb_green",
    "hlc_rifle_ACR_GL_Carb_tan",

    "hlc_rifle_ACR_MID_black",
    "hlc_rifle_ACR_MID_black_grip",
    "hlc_rifle_ACR_MID_black_grip2",
    "hlc_rifle_ACR_MID_black_grip3",
    "hlc_rifle_ACR_MID_black_x15",
    "hlc_rifle_ACR_MID_black_x15_grip",
    "hlc_rifle_ACR_MID_black_x15_grip2",
    "hlc_rifle_ACR_MID_black_x15_grip3",

    "hlc_rifle_ACR_MID_green",
    "hlc_rifle_ACR_MID_green_grip",
    "hlc_rifle_ACR_MID_green_grip2",
    "hlc_rifle_ACR_MID_green_grip3",
    "hlc_rifle_ACR_MID_green_x15",
    "hlc_rifle_ACR_MID_green_x15_grip",
    "hlc_rifle_ACR_MID_green_x15_grip2",
    "hlc_rifle_ACR_MID_green_x15_grip3",

    "hlc_rifle_ACR_MID_tan",
    "hlc_rifle_ACR_MID_tan_grip",
    "hlc_rifle_ACR_MID_tan_grip2",
    "hlc_rifle_ACR_MID_tan_grip3",
    "hlc_rifle_ACR_MID_tan_x15",
    "hlc_rifle_ACR_MID_tan_x15_grip",
    "hlc_rifle_ACR_MID_tan_x15_grip2",
    "hlc_rifle_ACR_MID_tan_x15_grip3",

    "hlc_rifle_ACR_GL_mid_black",
    "hlc_rifle_ACR_GL_mid_green",
    "hlc_rifle_ACR_GL_mid_tan",

    "hlc_rifle_ACR68_MID_black",
    "hlc_rifle_ACR68_MID_black_grip",
    "hlc_rifle_ACR68_MID_black_grip2",
    "hlc_rifle_ACR68_MID_black_grip3",

    "hlc_rifle_ACR68_MID_green",
    "hlc_rifle_ACR68_MID_green_grip",
    "hlc_rifle_ACR68_MID_green_grip2",
    "hlc_rifle_ACR68_MID_green_grip3",

    "hlc_rifle_ACR68_MID_tan",
    "hlc_rifle_ACR68_MID_tan_grip",
    "hlc_rifle_ACR68_MID_tan_grip2",
    "hlc_rifle_ACR68_MID_tan_grip3",

    "hlc_rifle_ACR68_GL_mid_black",
    "hlc_rifle_ACR68_GL_mid_green",
    "hlc_rifle_ACR68_GL_mid_tan",

    "hlc_rifle_ACR_full_black",
    "hlc_rifle_ACR_Full_black_grip",
    "hlc_rifle_ACR_Full_black_grip2",
    "hlc_rifle_ACR_Full_black_grip3",
    "hlc_rifle_ACR_full_black_x15",
    "hlc_rifle_ACR_Full_black_x15_grip",
    "hlc_rifle_ACR_Full_black_x15_grip2",
    "hlc_rifle_ACR_Full_black_x15_grip3",

    "hlc_rifle_ACR_full_green",
    "hlc_rifle_ACR_Full_green_grip",
    "hlc_rifle_ACR_Full_green_grip2",
    "hlc_rifle_ACR_Full_green_grip3",
    "hlc_rifle_ACR_full_green_x15",
    "hlc_rifle_ACR_Full_green_x15_grip",
    "hlc_rifle_ACR_Full_green_x15_grip2",
    "hlc_rifle_ACR_Full_green_x15_grip3",

    "hlc_rifle_ACR_full_tan",
    "hlc_rifle_ACR_Full_tan_grip",
    "hlc_rifle_ACR_Full_tan_grip2",
    "hlc_rifle_ACR_Full_tan_grip3",
    "hlc_rifle_ACR_full_tan_x15",
    "hlc_rifle_ACR_Full_tan_x15_grip",
    "hlc_rifle_ACR_Full_tan_x15_grip2",
    "hlc_rifle_ACR_Full_tan_x15_grip3",

    "hlc_rifle_ACR68_full_black",
    "hlc_rifle_ACR68_full_black_grip",
    "hlc_rifle_ACR68_full_black_grip2",
    "hlc_rifle_ACR68_full_black_grip3",

    "hlc_rifle_ACR68_full_green",
    "hlc_rifle_ACR68_full_green_grip",
    "hlc_rifle_ACR68_full_green_grip2",
    "hlc_rifle_ACR68_full_green_grip3",

    "hlc_rifle_ACR68_full_tan",
    "hlc_rifle_ACR68_full_tan_grip",
    "hlc_rifle_ACR68_full_tan_grip2",
    "hlc_rifle_ACR68_full_tan_grip3"
];

hlc_barrel_mid_ACR_68_compatible_weapons = [
    "hlc_rifle_ACR_SBR_black",
    "hlc_rifle_ACR_SBR_black_grip",
    "hlc_rifle_ACR_SBR_black_grip2",
    "hlc_rifle_ACR_SBR_black_grip3",
    "hlc_rifle_ACR_SBR_black_x15",
    "hlc_rifle_ACR_SBR_black_x15_grip",
    "hlc_rifle_ACR_SBR_black_x15_grip2",
    "hlc_rifle_ACR_SBR_black_x15_grip3",

    "hlc_rifle_ACR_SBR_green",
    "hlc_rifle_ACR_SBR_green_grip",
    "hlc_rifle_ACR_SBR_green_grip2",
    "hlc_rifle_ACR_SBR_green_grip3",
    "hlc_rifle_ACR_SBR_green_x15",
    "hlc_rifle_ACR_SBR_green_x15_grip",
    "hlc_rifle_ACR_SBR_green_x15_grip2",
    "hlc_rifle_ACR_SBR_green_x15_grip3",

    "hlc_rifle_ACR_SBR_tan",
    "hlc_rifle_ACR_SBR_tan_grip",
    "hlc_rifle_ACR_SBR_tan_grip2",
    "hlc_rifle_ACR_SBR_tan_grip3",
    "hlc_rifle_ACR_SBR_tan_x15",
    "hlc_rifle_ACR_SBR_tan_x15_grip",
    "hlc_rifle_ACR_SBR_tan_x15_grip2",
    "hlc_rifle_ACR_SBR_tan_x15_grip3",

    "hlc_rifle_ACR_GL_SBR_black",
    "hlc_rifle_ACR_GL_SBR_green",
    "hlc_rifle_ACR_GL_SBR_tan",

    "hlc_rifle_ACR68_SBR_black",
    "hlc_rifle_ACR68_SBR_black_grip",
    "hlc_rifle_ACR68_SBR_black_grip2",
    "hlc_rifle_ACR68_SBR_black_grip3",

    "hlc_rifle_ACR68_SBR_green",
    "hlc_rifle_ACR68_SBR_green_grip",
    "hlc_rifle_ACR68_SBR_green_grip2",
    "hlc_rifle_ACR68_SBR_green_grip3",

    "hlc_rifle_ACR68_SBR_tan",
    "hlc_rifle_ACR68_SBR_tan_grip",
    "hlc_rifle_ACR68_SBR_tan_grip2",
    "hlc_rifle_ACR68_SBR_tan_grip3",

    "hlc_rifle_ACR68_GL_SBR_black",
    "hlc_rifle_ACR68_GL_SBR_green",
    "hlc_rifle_ACR68_GL_SBR_tan",

    "hlc_rifle_ACR_Carb_black",
    "hlc_rifle_ACR_carb_black_grip",
    "hlc_rifle_ACR_carb_black_grip2",
    "hlc_rifle_ACR_carb_black_grip3",
    "hlc_rifle_ACR_Carb_black_x15",
    "hlc_rifle_ACR_carb_black_x15_grip",
    "hlc_rifle_ACR_carb_black_x15_grip2",
    "hlc_rifle_ACR_carb_black_x15_grip3",

    "hlc_rifle_ACR_Carb_green",
    "hlc_rifle_ACR_carb_green_grip",
    "hlc_rifle_ACR_carb_green_grip2",
    "hlc_rifle_ACR_carb_green_grip3",
    "hlc_rifle_ACR_Carb_green_x15",
    "hlc_rifle_ACR_carb_green_x15_grip",
    "hlc_rifle_ACR_carb_green_x15_grip2",
    "hlc_rifle_ACR_carb_green_x15_grip3",

    "hlc_rifle_ACR_Carb_tan",
    "hlc_rifle_ACR_carb_tan_grip",
    "hlc_rifle_ACR_carb_tan_grip2",
    "hlc_rifle_ACR_carb_tan_grip3",
    "hlc_rifle_ACR_Carb_tan_x15",
    "hlc_rifle_ACR_carb_tan_x15_grip",
    "hlc_rifle_ACR_carb_tan_x15_grip2",
    "hlc_rifle_ACR_carb_tan_x15_grip3",

    "hlc_rifle_ACR_GL_Carb_black",
    "hlc_rifle_ACR_GL_Carb_green",
    "hlc_rifle_ACR_GL_Carb_tan",

    "hlc_rifle_ACR68_Carb_black",
    "hlc_rifle_ACR68_carb_black_grip",
    "hlc_rifle_ACR68_carb_black_grip2",
    "hlc_rifle_ACR68_carb_black_grip3",

    "hlc_rifle_ACR68_Carb_green",
    "hlc_rifle_ACR68_carb_green_grip",
    "hlc_rifle_ACR68_carb_green_grip2",
    "hlc_rifle_ACR68_carb_green_grip3",

    "hlc_rifle_ACR68_Carb_tan",
    "hlc_rifle_ACR68_carb_tan_grip",
    "hlc_rifle_ACR68_carb_tan_grip2",
    "hlc_rifle_ACR68_carb_tan_grip3",

    "hlc_rifle_ACR68_GL_Carb_black",
    "hlc_rifle_ACR68_GL_Carb_green",
    "hlc_rifle_ACR68_GL_Carb_tan",

    "hlc_rifle_ACR_MID_black",
    "hlc_rifle_ACR_MID_black_grip",
    "hlc_rifle_ACR_MID_black_grip2",
    "hlc_rifle_ACR_MID_black_grip3",
    "hlc_rifle_ACR_MID_black_x15",
    "hlc_rifle_ACR_MID_black_x15_grip",
    "hlc_rifle_ACR_MID_black_x15_grip2",
    "hlc_rifle_ACR_MID_black_x15_grip3",

    "hlc_rifle_ACR_MID_green",
    "hlc_rifle_ACR_MID_green_grip",
    "hlc_rifle_ACR_MID_green_grip2",
    "hlc_rifle_ACR_MID_green_grip3",
    "hlc_rifle_ACR_MID_green_x15",
    "hlc_rifle_ACR_MID_green_x15_grip",
    "hlc_rifle_ACR_MID_green_x15_grip2",
    "hlc_rifle_ACR_MID_green_x15_grip3",

    "hlc_rifle_ACR_MID_tan",
    "hlc_rifle_ACR_MID_tan_grip",
    "hlc_rifle_ACR_MID_tan_grip2",
    "hlc_rifle_ACR_MID_tan_grip3",
    "hlc_rifle_ACR_MID_tan_x15",
    "hlc_rifle_ACR_MID_tan_x15_grip",
    "hlc_rifle_ACR_MID_tan_x15_grip2",
    "hlc_rifle_ACR_MID_tan_x15_grip3",

    "hlc_rifle_ACR_GL_mid_black",
    "hlc_rifle_ACR_GL_mid_green",
    "hlc_rifle_ACR_GL_mid_tan",

    "hlc_rifle_ACR_full_black",
    "hlc_rifle_ACR_Full_black_grip",
    "hlc_rifle_ACR_Full_black_grip2",
    "hlc_rifle_ACR_Full_black_grip3",
    "hlc_rifle_ACR_full_black_x15",
    "hlc_rifle_ACR_Full_black_x15_grip",
    "hlc_rifle_ACR_Full_black_x15_grip2",
    "hlc_rifle_ACR_Full_black_x15_grip3",

    "hlc_rifle_ACR_full_green",
    "hlc_rifle_ACR_Full_green_grip",
    "hlc_rifle_ACR_Full_green_grip2",
    "hlc_rifle_ACR_Full_green_grip3",
    "hlc_rifle_ACR_full_green_x15",
    "hlc_rifle_ACR_Full_green_x15_grip",
    "hlc_rifle_ACR_Full_green_x15_grip2",
    "hlc_rifle_ACR_Full_green_x15_grip3",

    "hlc_rifle_ACR_full_tan",
    "hlc_rifle_ACR_Full_tan_grip",
    "hlc_rifle_ACR_Full_tan_grip2",
    "hlc_rifle_ACR_Full_tan_grip3",
    "hlc_rifle_ACR_full_tan_x15",
    "hlc_rifle_ACR_Full_tan_x15_grip",
    "hlc_rifle_ACR_Full_tan_x15_grip2",
    "hlc_rifle_ACR_Full_tan_x15_grip3",

    "hlc_rifle_ACR68_full_black",
    "hlc_rifle_ACR68_full_black_grip",
    "hlc_rifle_ACR68_full_black_grip2",
    "hlc_rifle_ACR68_full_black_grip3",

    "hlc_rifle_ACR68_full_green",
    "hlc_rifle_ACR68_full_green_grip",
    "hlc_rifle_ACR68_full_green_grip2",
    "hlc_rifle_ACR68_full_green_grip3",

    "hlc_rifle_ACR68_full_tan",
    "hlc_rifle_ACR68_full_tan_grip",
    "hlc_rifle_ACR68_full_tan_grip2",
    "hlc_rifle_ACR68_full_tan_grip3"
];

hlc_barrel_full_ACR_68_compatible_weapons = [
    "hlc_rifle_ACR_SBR_black",
    "hlc_rifle_ACR_SBR_black_grip",
    "hlc_rifle_ACR_SBR_black_grip2",
    "hlc_rifle_ACR_SBR_black_grip3",
    "hlc_rifle_ACR_SBR_black_x15",
    "hlc_rifle_ACR_SBR_black_x15_grip",
    "hlc_rifle_ACR_SBR_black_x15_grip2",
    "hlc_rifle_ACR_SBR_black_x15_grip3",

    "hlc_rifle_ACR_SBR_green",
    "hlc_rifle_ACR_SBR_green_grip",
    "hlc_rifle_ACR_SBR_green_grip2",
    "hlc_rifle_ACR_SBR_green_grip3",
    "hlc_rifle_ACR_SBR_green_x15",
    "hlc_rifle_ACR_SBR_green_x15_grip",
    "hlc_rifle_ACR_SBR_green_x15_grip2",
    "hlc_rifle_ACR_SBR_green_x15_grip3",

    "hlc_rifle_ACR_SBR_tan",
    "hlc_rifle_ACR_SBR_tan_grip",
    "hlc_rifle_ACR_SBR_tan_grip2",
    "hlc_rifle_ACR_SBR_tan_grip3",
    "hlc_rifle_ACR_SBR_tan_x15",
    "hlc_rifle_ACR_SBR_tan_x15_grip",
    "hlc_rifle_ACR_SBR_tan_x15_grip2",
    "hlc_rifle_ACR_SBR_tan_x15_grip3",

    "hlc_rifle_ACR_GL_SBR_black",
    "hlc_rifle_ACR_GL_SBR_green",
    "hlc_rifle_ACR_GL_SBR_tan",

    "hlc_rifle_ACR68_SBR_black",
    "hlc_rifle_ACR68_SBR_black_grip",
    "hlc_rifle_ACR68_SBR_black_grip2",
    "hlc_rifle_ACR68_SBR_black_grip3",

    "hlc_rifle_ACR68_SBR_green",
    "hlc_rifle_ACR68_SBR_green_grip",
    "hlc_rifle_ACR68_SBR_green_grip2",
    "hlc_rifle_ACR68_SBR_green_grip3",

    "hlc_rifle_ACR68_SBR_tan",
    "hlc_rifle_ACR68_SBR_tan_grip",
    "hlc_rifle_ACR68_SBR_tan_grip2",
    "hlc_rifle_ACR68_SBR_tan_grip3",

    "hlc_rifle_ACR68_GL_SBR_black",
    "hlc_rifle_ACR68_GL_SBR_green",
    "hlc_rifle_ACR68_GL_SBR_tan",

    "hlc_rifle_ACR_Carb_black",
    "hlc_rifle_ACR_carb_black_grip",
    "hlc_rifle_ACR_carb_black_grip2",
    "hlc_rifle_ACR_carb_black_grip3",
    "hlc_rifle_ACR_Carb_black_x15",
    "hlc_rifle_ACR_carb_black_x15_grip",
    "hlc_rifle_ACR_carb_black_x15_grip2",
    "hlc_rifle_ACR_carb_black_x15_grip3",

    "hlc_rifle_ACR_Carb_green",
    "hlc_rifle_ACR_carb_green_grip",
    "hlc_rifle_ACR_carb_green_grip2",
    "hlc_rifle_ACR_carb_green_grip3",
    "hlc_rifle_ACR_Carb_green_x15",
    "hlc_rifle_ACR_carb_green_x15_grip",
    "hlc_rifle_ACR_carb_green_x15_grip2",
    "hlc_rifle_ACR_carb_green_x15_grip3",

    "hlc_rifle_ACR_Carb_tan",
    "hlc_rifle_ACR_carb_tan_grip",
    "hlc_rifle_ACR_carb_tan_grip2",
    "hlc_rifle_ACR_carb_tan_grip3",
    "hlc_rifle_ACR_Carb_tan_x15",
    "hlc_rifle_ACR_carb_tan_x15_grip",
    "hlc_rifle_ACR_carb_tan_x15_grip2",
    "hlc_rifle_ACR_carb_tan_x15_grip3",

    "hlc_rifle_ACR_GL_Carb_black",
    "hlc_rifle_ACR_GL_Carb_green",
    "hlc_rifle_ACR_GL_Carb_tan",

    "hlc_rifle_ACR68_Carb_black",
    "hlc_rifle_ACR68_carb_black_grip",
    "hlc_rifle_ACR68_carb_black_grip2",
    "hlc_rifle_ACR68_carb_black_grip3",

    "hlc_rifle_ACR68_Carb_green",
    "hlc_rifle_ACR68_carb_green_grip",
    "hlc_rifle_ACR68_carb_green_grip2",
    "hlc_rifle_ACR68_carb_green_grip3",

    "hlc_rifle_ACR68_Carb_tan",
    "hlc_rifle_ACR68_carb_tan_grip",
    "hlc_rifle_ACR68_carb_tan_grip2",
    "hlc_rifle_ACR68_carb_tan_grip3",

    "hlc_rifle_ACR68_GL_Carb_black",
    "hlc_rifle_ACR68_GL_Carb_green",
    "hlc_rifle_ACR68_GL_Carb_tan",

    "hlc_rifle_ACR_MID_black",
    "hlc_rifle_ACR_MID_black_grip",
    "hlc_rifle_ACR_MID_black_grip2",
    "hlc_rifle_ACR_MID_black_grip3",
    "hlc_rifle_ACR_MID_black_x15",
    "hlc_rifle_ACR_MID_black_x15_grip",
    "hlc_rifle_ACR_MID_black_x15_grip2",
    "hlc_rifle_ACR_MID_black_x15_grip3",

    "hlc_rifle_ACR_MID_green",
    "hlc_rifle_ACR_MID_green_grip",
    "hlc_rifle_ACR_MID_green_grip2",
    "hlc_rifle_ACR_MID_green_grip3",
    "hlc_rifle_ACR_MID_green_x15",
    "hlc_rifle_ACR_MID_green_x15_grip",
    "hlc_rifle_ACR_MID_green_x15_grip2",
    "hlc_rifle_ACR_MID_green_x15_grip3",

    "hlc_rifle_ACR_MID_tan",
    "hlc_rifle_ACR_MID_tan_grip",
    "hlc_rifle_ACR_MID_tan_grip2",
    "hlc_rifle_ACR_MID_tan_grip3",
    "hlc_rifle_ACR_MID_tan_x15",
    "hlc_rifle_ACR_MID_tan_x15_grip",
    "hlc_rifle_ACR_MID_tan_x15_grip2",
    "hlc_rifle_ACR_MID_tan_x15_grip3",

    "hlc_rifle_ACR_GL_mid_black",
    "hlc_rifle_ACR_GL_mid_green",
    "hlc_rifle_ACR_GL_mid_tan",

    "hlc_rifle_ACR68_MID_black",
    "hlc_rifle_ACR68_MID_black_grip",
    "hlc_rifle_ACR68_MID_black_grip2",
    "hlc_rifle_ACR68_MID_black_grip3",

    "hlc_rifle_ACR68_MID_green",
    "hlc_rifle_ACR68_MID_green_grip",
    "hlc_rifle_ACR68_MID_green_grip2",
    "hlc_rifle_ACR68_MID_green_grip3",

    "hlc_rifle_ACR68_MID_tan",
    "hlc_rifle_ACR68_MID_tan_grip",
    "hlc_rifle_ACR68_MID_tan_grip2",
    "hlc_rifle_ACR68_MID_tan_grip3",

    "hlc_rifle_ACR68_GL_mid_black",
    "hlc_rifle_ACR68_GL_mid_green",
    "hlc_rifle_ACR68_GL_mid_tan",

    "hlc_rifle_ACR_full_black",
    "hlc_rifle_ACR_Full_black_grip",
    "hlc_rifle_ACR_Full_black_grip2",
    "hlc_rifle_ACR_Full_black_grip3",
    "hlc_rifle_ACR_full_black_x15",
    "hlc_rifle_ACR_Full_black_x15_grip",
    "hlc_rifle_ACR_Full_black_x15_grip2",
    "hlc_rifle_ACR_Full_black_x15_grip3",

    "hlc_rifle_ACR_full_green",
    "hlc_rifle_ACR_Full_green_grip",
    "hlc_rifle_ACR_Full_green_grip2",
    "hlc_rifle_ACR_Full_green_grip3",
    "hlc_rifle_ACR_full_green_x15",
    "hlc_rifle_ACR_Full_green_x15_grip",
    "hlc_rifle_ACR_Full_green_x15_grip2",
    "hlc_rifle_ACR_Full_green_x15_grip3",

    "hlc_rifle_ACR_full_tan",
    "hlc_rifle_ACR_Full_tan_grip",
    "hlc_rifle_ACR_Full_tan_grip2",
    "hlc_rifle_ACR_Full_tan_grip3",
    "hlc_rifle_ACR_full_tan_x15",
    "hlc_rifle_ACR_Full_tan_x15_grip",
    "hlc_rifle_ACR_Full_tan_x15_grip2",
    "hlc_rifle_ACR_Full_tan_x15_grip3"
];

if (!isClass (configFile >> "CfgPatches" >> "ace_interaction")) then {
	   HLC_ShowBarrelActions = true;
    HLC_ShowBarrelAceActions = false;
} else {
	   HLC_ShowBarrelActions = false;
    HLC_ShowBarrelAceActions = true;
};